### ISSUE TITLE
Extend Support for Video Front End Editor and Uploader

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/Restrict-Taxonomies#1]
There are certain channels on our Video Portal that should only be available to a select group of admin users on the site, rather than open to all authors. This plugin creates that option within the admin panel, but doesn't extend out into our front end editor and Upload functionality (we would also need this to extend to the D2L Insert Stuff window). 

Could we add additional options so the plugin doesn't bail if we aren't in admin, to extend to `WP_Frontend_Admin_Screen` and the D2L Insert Stuff logic?

**Comment by r-a-y** [comment]
Should work now.

Give it a try and let me know if everything is working.

**Comment by mrjarbenne** [comment]
Working great. Thanks for that.
